### ISSUE TITLE
Updating a user needs refactoring

### ISSUE THREAD

**Issue by jfrazier312** [boyangles/ece-inventory-app#10]
page breaks on update user

need to show privilege option only for an admin user attempting to update a student to TA or to admin

need to show password and password confirmation boxes

**Comment by boyangles** [comment]
I'm on it

**Comment by boyangles** [comment]
+ page no longer breaks on update user
- showing privilege options only for admin user not done yet (pretty easy though, i think)
+ password confirmation box completed

**Comment by boyangles** [comment]
The 2nd bullet point is not technically in the milestone #1 requirements, and I did the 1st and 3rd bullets, so I'm gonna close this issue
