### ISSUE TITLE
Bug with updating existing entries (pre-status migration ones) in User table

### ISSUE THREAD

**Issue by boyangles** [boyangles/ece-inventory-app#13]
Usually a user updating his own credentials have no power over his status/privilege, so if it is nil existing in the database initially, then there will be a null pointer exception.
![selection_016](https://cloud.githubusercontent.com/assets/22850436/22242618/fd5cc16e-e1f1-11e6-88c0-8563491cf875.png)

**Comment by jfrazier312** [comment]
Shouldn't this be solved by just dropping our database for this one?
