### ISSUE TITLE
Get rid of the pane at the bottom of each page ?

### ISSUE THREAD

**Issue by joshuaxu1995** [boyangles/ece-inventory-app#42]
<img width="1019" alt="screen shot 2017-02-01 at 2 41 02 pm" src="https://cloud.githubusercontent.com/assets/16597010/22523187/70f7ac24-e88c-11e6-852e-9602b037f4a3.png">

**Comment by jfrazier312** [comment]
thats the debugger pane @joshuaxu1995. it's only on testing environments.
